# =============================================================================
# plot_paper_sigma_estimates.gp
#
# Plots per-cycle calibrated noise-std estimates (sigma_j) for the three
# calibrated observation channels in the Bioretention twin experiment, all
# on a single panel with log-scaled y so channels of widely different
# magnitudes share the figure cleanly.
#
# There is no point-truth value for sigma; the synthetic observation noise
# is generated by a correlated Ornstein-Uhlenbeck process applied
# log-normally, so what the calibration recovers is an effective
# stationary scale per channel rather than a fixed reference.
#
# Inputs:
#   Bioretention_assimilation/outputs/calibration/parameter_history.csv
#
# Output:
#   paper_sigma_estimates.png
#
# Run from the deployments/ directory:
#   gnuplot plot_paper_sigma_estimates.gp
# =============================================================================

set datafile separator ","
set datafile missing "nan"

infile  = "Bioretention_assimilation/outputs/calibration/parameter_history.csv"
outfile = "paper_sigma_estimates.png"

if (!exists("drift")) drift = 0
if (drift) {
    infile  = "Bioretention_assimilation_drift/outputs/calibration/parameter_history.csv"
    outfile = "paper_sigma_estimates_drift.png"
}

# --- output canvas ----------------------------------------------------------
set terminal pngcairo size 1100,650 enhanced font "Helvetica,18"
set output outfile

# --- x-axis: simulated calendar date ---------------------------------------
epoch(d) = (d - 25569.0) * 86400.0
set xdata time
set timefmt "%s"
set format x "%Y-%m"
set xtics 10368000   # 120 days ≈ 4 months
set xlabel "Simulated date" offset 0,-0.5

# --- y-axis: log-scaled ----------------------------------------------------
set logscale y
set format y "10^{%T}"
set ylabel "Estimated {/Symbol s}_j (channel-native units)" offset 1,0
set yrange [*:*]
set ytics autofreq

# --- style -----------------------------------------------------------------
set grid xtics ytics lc rgb "#cccccc" lw 0.8
set tics nomirror
set border 3

set key top right inside box opaque samplen 2 spacing 1.2 \
    font "Helvetica,16" width 0

c_pond  = "#1f77b4"
c_soil  = "#2ca02c"
c_under = "#d62728"

ps = 1.0
lw_line = 2.2

set title "Estimated channel noise standard deviations" font "Helvetica,18"

# Columns in parameter_history.csv:
#   1: cycle
#   2: timestamp
#   3: t_now
#   4: EngineeredSoilKsat
#   5: Evap_Coeff
#   6: NativeSoilAlpha
#   7: NativeSoilKsat
#   8: Std_PondWaterDepth
#   9: Std_SoilMoisture
#  10: Std_UnderdrainFlow

plot \
    infile using (epoch($3)):8  with linespoints \
        lc rgb c_pond  lw lw_line pt 7 ps ps title "Pond water depth", \
    infile using (epoch($3)):9  with linespoints \
        lc rgb c_soil  lw lw_line pt 5 ps ps title "Soil moisture", \
    infile using (epoch($3)):10 with linespoints \
        lc rgb c_under lw lw_line pt 9 ps ps title "Underdrain flow"

unset output
