// Auto-generated by OpenHydroQual model compiler (Export to C++). Do not edit.
#include "Wetland_api.h"
#include "Wetland.h"

struct Wetland_handle { Wetland m; };

extern "C" {
Wetland_handle* Wetland_create(void) { return new Wetland_handle(); }
void   Wetland_destroy(Wetland_handle* h) { delete h; }
void   Wetland_initialize(Wetland_handle* h) { h->m.initialize(); }
void   Wetland_initialize_at(Wetland_handle* h, double tstart, double dt0) { h->m.initialize(tstart, dt0); }
int    Wetland_step(Wetland_handle* h) { return h->m.step() ? 1 : 0; }
int    Wetland_step_to(Wetland_handle* h, double t) { return h->m.stepTo(t) ? 1 : 0; }
int    Wetland_run_to(Wetland_handle* h, double t) { return h->m.runTo(t) ? 1 : 0; }
double Wetland_time(const Wetland_handle* h) { return h->m.time(); }
int    Wetland_n_states(void) { return Wetland::N_STATES; }
double Wetland_state(const Wetland_handle* h, int i) { return h->m.state(i); }
const char* Wetland_state_name(int i) { return Wetland::stateName(i); }
double Wetland_simulation_start(void) { return Wetland::simulationStart(); }
double Wetland_simulation_end(void) { return Wetland::simulationEnd(); }
int    Wetland_n_parameters(void) { return Wetland::N_PARAMETERS; }
const char* Wetland_parameter_name(int i) { return Wetland::parameterName(i); }
double Wetland_parameter(const Wetland_handle* h, int i) { return h->m.parameter(i); }
void   Wetland_set_parameter(Wetland_handle* h, int i, double v) { h->m.setParameter(i, v); }
void   Wetland_apply_parameters(Wetland_handle* h) { h->m.applyParameters(); }
int    Wetland_n_observations(void) { return Wetland::N_OBSERVATIONS; }
const char* Wetland_observation_name(int i) { return Wetland::observationName(i); }
int    Wetland_observation_count(const Wetland_handle* h, int i) { return (int)h->m.observationSeries(i).size(); }
int    Wetland_observation_at(const Wetland_handle* h, int i, int k, double* t, double* v) {
    const ohq::TimeSeries& s = h->m.observationSeries(i); if (k < 0 || k >= (int)s.size()) return 0; *t = s.t[k]; *v = s.c[k]; return 1; }
void   Wetland_clear_observations(Wetland_handle* h) { h->m.clearObservations(); }
int    Wetland_solution_failed(const Wetland_handle* h) { return h->m.solutionFailed() ? 1 : 0; }
double Wetland_simulation_duration(const Wetland_handle* h) { return h->m.simulationDuration(); }
long   Wetland_step_count(const Wetland_handle* h) { return h->m.stepCount(); }
int    Wetland_last_iterations(const Wetland_handle* h) { return h->m.lastIterations(); }
void   Wetland_reset_status(Wetland_handle* h) { h->m.resetStatus(); }
int    Wetland_n_series(void) { return Wetland::N_SERIES; }
const char* Wetland_series_object(int k) { return Wetland::seriesObject(k); }
const char* Wetland_series_quantity(int k) { return Wetland::seriesQuantity(k); }
int    Wetland_set_series(Wetland_handle* h, const char* o, const char* q, const double* t, const double* v, int n) { return h->m.setSeries(o, q, t, v, n) ? 1 : 0; }
int    Wetland_set_precipitation(Wetland_handle* h, const char* o, const char* q, const double* s, const double* e, const double* d, int n) { return h->m.setPrecipitation(o, q, s, e, d, n) ? 1 : 0; }
void   Wetland_export_state(const Wetland_handle* h, double* st, double* ma, int* li, double* lf) { h->m.exportState(st, ma, li, lf); }
void   Wetland_import_state(Wetland_handle* h, double t, const double* st, const double* ma, const int* li, const double* lf) { h->m.importState(t, st, ma, li, lf); }
int    Wetland_n_mass(void) { return Wetland::N_MASS; }
double Wetland_mass(const Wetland_handle* h, int i) { return h->m.constMass(i); }

/* ---- model-independent alias ABI -------------------------------------
   The names above carry the class name, so a host that dlopen()s the
   library would have to know it. These fixed names let a generic host
   (OHQ-GA / OHQ-MCMC --kernel) drive ANY generated model. Keep in sync
   with tools/ohq_kernel.h. ohq_kernel_abi_version() guards changes. */
int    ohq_kernel_abi_version(void) { return 2; }   /* v2: + G4 forcing, G5 state, status, state/mass readback */
const char* ohq_kernel_class_name(void) { return "Wetland"; }
void*  ohq_kernel_create(void) { return (void*)Wetland_create(); }
void   ohq_kernel_destroy(void* h) { Wetland_destroy((Wetland_handle*)h); }
void   ohq_kernel_initialize(void* h) { Wetland_initialize((Wetland_handle*)h); }
int    ohq_kernel_run_to(void* h, double t) { return Wetland_run_to((Wetland_handle*)h, t); }
/* One accepted step, dt clamped so it never crosses t_end. A host that
   must honour a wall-clock budget (System::Solve aborts at
   maximum_time_allowed) steps with this instead of run_to, which has no
   cancellation: a parameter set that collapses dt to the floor would
   otherwise run for millions of steps with no way out. */
int    ohq_kernel_step_to(void* h, double t) { return Wetland_step_to((Wetland_handle*)h, t); }
double ohq_kernel_time(const void* h) { return Wetland_time((const Wetland_handle*)h); }
double ohq_kernel_simulation_start(void) { return Wetland_simulation_start(); }
double ohq_kernel_simulation_end(void) { return Wetland_simulation_end(); }
int    ohq_kernel_n_parameters(void) { return Wetland_n_parameters(); }
const char* ohq_kernel_parameter_name(int i) { return Wetland_parameter_name(i); }
void   ohq_kernel_set_parameter(void* h, int i, double v) { Wetland_set_parameter((Wetland_handle*)h, i, v); }
void   ohq_kernel_apply_parameters(void* h) { Wetland_apply_parameters((Wetland_handle*)h); }
int    ohq_kernel_n_observations(void) { return Wetland_n_observations(); }
const char* ohq_kernel_observation_name(int i) { return Wetland_observation_name(i); }
int    ohq_kernel_observation_count(const void* h, int i) { return Wetland_observation_count((const Wetland_handle*)h, i); }
int    ohq_kernel_observation_at(const void* h, int i, int k, double* t, double* v) { return Wetland_observation_at((const Wetland_handle*)h, i, k, t, v); }
void   ohq_kernel_clear_observations(void* h) { Wetland_clear_observations((Wetland_handle*)h); }
int    ohq_kernel_solution_failed(const void* h) { return Wetland_solution_failed((const Wetland_handle*)h); }
double ohq_kernel_simulation_duration(const void* h) { return Wetland_simulation_duration((const Wetland_handle*)h); }
long   ohq_kernel_step_count(const void* h) { return Wetland_step_count((const Wetland_handle*)h); }
int    ohq_kernel_last_iterations(const void* h) { return Wetland_last_iterations((const Wetland_handle*)h); }
void   ohq_kernel_reset_status(void* h) { Wetland_reset_status((Wetland_handle*)h); }
/* System::FinalizeOutputs uniformizes ObservedOutputs with dt0 before the
   objective is computed (Objective_Function.cpp:133); a host scoring the
   kernel must do the same or it compares on a different grid. */
void   ohq_kernel_uniformize_observations(void* h) { ((Wetland_handle*)h)->m.uniformizeObservations(); }
/* state vector (read results / drive an export) */
int    ohq_kernel_n_states(void) { return Wetland_n_states(); }
double ohq_kernel_state(const void* h, int i) { return Wetland_state((const Wetland_handle*)h, i); }
const char* ohq_kernel_state_name(int i) { return Wetland_state_name(i); }
int    ohq_kernel_step(void* h) { return Wetland_step((Wetland_handle*)h); }
void   ohq_kernel_initialize_at(void* h, double tstart, double dt0) { Wetland_initialize_at((Wetland_handle*)h, tstart, dt0); }
double ohq_kernel_parameter(const void* h, int i) { return Wetland_parameter((const Wetland_handle*)h, i); }
/* G4: runtime forcing injection, addressed by (object, quantity) name */
int    ohq_kernel_n_series(void) { return Wetland_n_series(); }
const char* ohq_kernel_series_object(int k) { return Wetland_series_object(k); }
const char* ohq_kernel_series_quantity(int k) { return Wetland_series_quantity(k); }
int    ohq_kernel_set_series(void* h, const char* o, const char* q, const double* t, const double* v, int n)
       { return Wetland_set_series((Wetland_handle*)h, o, q, t, v, n); }
int    ohq_kernel_set_precipitation(void* h, const char* o, const char* q, const double* s, const double* e, const double* d, int n)
       { return Wetland_set_precipitation((Wetland_handle*)h, o, q, s, e, d, n); }
/* G5: state VALUES in/out (hot restart); mass/limited/limitFactor may be NULL */
void   ohq_kernel_export_state(const void* h, double* st, double* ma, int* li, double* lf)
       { Wetland_export_state((const Wetland_handle*)h, st, ma, li, lf); }
void   ohq_kernel_import_state(void* h, double t, const double* st, const double* ma, const int* li, const double* lf)
       { Wetland_import_state((Wetland_handle*)h, t, st, ma, li, lf); }
/* constituents: always present in the ABI; 0 / 0.0 when the model has none */
int    ohq_kernel_n_mass(void) { return Wetland_n_mass(); }
double ohq_kernel_mass(const void* h, int i) { return Wetland_mass((const Wetland_handle*)h, i); }
}
