#!/usr/bin/env python3
"""Normalize Wetland truth/MCMC/reanalysis outputs for robust Gnuplot use."""
from __future__ import annotations
import argparse, csv, math, re, sys
from pathlib import Path

VARIABLES = {
    "precip": ["precipitation"],
    "inflow": ["wetland inflow"],
    "inlet_stage": ["wetland inlet stage", "inlet stage"],
    "mid_stage": ["wetland mid-stage", "wetland mid stage", "mid-stage", "mid stage"],
    "outlet_stage": ["wetland outlet stage", "outlet stage"],
    "outflow": ["wetland outflow", "outflow"],
    "cell1_depth": ["cell 1 water depth", "cell 1 depth", "cell1"],
    "cell6_depth": ["cell 6 water depth", "cell 6 depth", "cell6"],
    "hrt": ["hrt"],
}
OUT_HEADER = ["time"] + list(VARIABLES)

def clean(s: str) -> str:
    s = re.sub(r"\([^)]*\)", "", s.strip().lower()).replace("_", " ")
    return re.sub(r"\s+", " ", s).strip()

def find_var_indices(header: list[str]) -> dict[str, tuple[int, int]]:
    h = [clean(x) for x in header]
    found = {}
    for var, keys in VARIABLES.items():
        for j, name in enumerate(h):
            if name == "t" or not name:
                continue
            if any(k in name for k in keys):
                found[var] = (j - 1 if j > 0 and h[j - 1] == "t" else 0, j)
                break
    return found

def normalize(src: Path, dst: Path, strict: bool) -> None:
    if not src.exists():
        print(f"[warn] missing input: {src}", file=sys.stderr)
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    with src.open(newline="", encoding="utf-8", errors="replace") as f:
        r = csv.reader(f)
        header = next(r, None)
        if header is None:
            raise ValueError(f"empty file: {src}")
        idx = find_var_indices(header)
        missing = [v for v in VARIABLES if v not in idx]
        if missing:
            msg = f"{src}: missing variables: {missing}; header={header}"
            if strict:
                raise KeyError(msg)
            print(f"[warn] {msg}", file=sys.stderr)
        t_idx = (idx.get("inlet_stage") or next(iter(idx.values()), (0, 0)))[0]
        with dst.open("w", newline="", encoding="utf-8") as out:
            w = csv.writer(out); w.writerow(OUT_HEADER)
            for row in r:
                if not row: continue
                values = [row[t_idx] if t_idx < len(row) else "nan"]
                for var in VARIABLES:
                    j = idx[var][1] if var in idx else -1
                    values.append(row[j] if 0 <= j < len(row) else "nan")
                w.writerow(values)
    print(f"[ok] wrote {dst}", file=sys.stderr)


def numeric_time_bounds(src: Path) -> tuple[float, float]:
    """Return finite minimum/maximum Excel-serial times from a normalized CSV."""
    if not src.exists():
        raise FileNotFoundError(f"missing normalized time-series file: {src}")
    times: list[float] = []
    with src.open(newline="", encoding="utf-8", errors="replace") as f:
        r = csv.DictReader(f)
        if "time" not in (r.fieldnames or []):
            raise KeyError(f"{src}: missing required 'time' column")
        for row in r:
            try:
                value = float(row.get("time", "nan"))
            except (TypeError, ValueError):
                continue
            if math.isfinite(value):
                times.append(value)
    if not times:
        raise ValueError(f"{src}: no finite time values")
    return min(times), max(times)


def write_window_config(src: Path, dst: Path, requested_days: float) -> None:
    """Write valid early/late Gnuplot windows derived from the current run."""
    t_min, t_max = numeric_time_bounds(src)
    duration = t_max - t_min
    if duration <= 0:
        raise ValueError(f"{src}: non-positive time span ({t_min} to {t_max})")

    requested_days = max(float(requested_days), 1.0 / 24.0)
    # Keep two non-overlapping windows whenever possible. For short runs, split
    # the available period into equal early and late halves.
    window_days = min(requested_days, duration / 2.0)
    x0, x1 = t_min, t_min + window_days
    x2, x3 = t_max - window_days, t_max

    dst.parent.mkdir(parents=True, exist_ok=True)
    with dst.open("w", encoding="utf-8") as f:
        f.write("# Auto-generated by prepare_wetland_mcmc_plot_inputs.py\n")
        f.write(f"# Source: {src.as_posix()}\n")
        f.write(f"# Available Excel-date range: {t_min:.10g} to {t_max:.10g}\n")
        f.write(f"window_days={window_days:.10g}\n")
        f.write(f"x0=epoch({x0:.10g})\n")
        f.write(f"x1=epoch({x1:.10g})\n")
        f.write(f"x2=epoch({x2:.10g})\n")
        f.write(f"x3=epoch({x3:.10g})\n")
    print(
        f"[ok] wrote {dst} "
        f"(early {x0:.5f}-{x1:.5f}; late {x2:.5f}-{x3:.5f})",
        file=sys.stderr,
    )

def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--truth", type=Path, default=Path("Wetland_truth/outputs/selected_output.csv"))
    p.add_argument("--mcmc", type=Path, default=Path("Wetland_assimilation_MCMC/outputs/selected_output.csv"))
    p.add_argument("--reanalysis", type=Path, default=Path("Wetland_assimilation_MCMC/outputs/reanalysis_output.csv"))
    p.add_argument("--outdir", type=Path, default=Path("Wetland_assimilation_MCMC/outputs/paper_plot_inputs_mcmc"))
    p.add_argument("--strict", action="store_true")
    p.add_argument("--window-days", type=float, default=10.0)
    p.add_argument("--window-config", type=Path, default=Path("plot_windows_wetland_mcmc.gp"))
    a = p.parse_args()
    normalize(a.truth, a.outdir / "truth_normalized_mcmc.csv", a.strict)
    normalize(a.mcmc, a.outdir / "mcmc_normalized.csv", a.strict)
    normalize(a.reanalysis, a.outdir / "reanalysis_normalized_mcmc.csv", a.strict)
    write_window_config(
        a.outdir / "mcmc_normalized.csv",
        a.window_config,
        a.window_days,
    )
    return 0
if __name__ == "__main__": raise SystemExit(main())
