// Auto-generated by OpenHydroQual model compiler (Export to C++). Do not edit.
// C API for the Wetland solver. Link the library and include this header.
#ifndef WETLAND_API_H
#define WETLAND_API_H

#if defined(_WIN32) && defined(WETLAND_SHARED)
#  ifdef WETLAND_EXPORTS
#    define WETLAND_API __declspec(dllexport)
#  else
#    define WETLAND_API __declspec(dllimport)
#  endif
#else
#  define WETLAND_API
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct Wetland_handle Wetland_handle;

/* lifecycle */
WETLAND_API Wetland_handle* Wetland_create(void);
WETLAND_API void   Wetland_destroy(Wetland_handle* h);
/* initialize at the model's own start time / initial dt, or at a given one */
WETLAND_API void   Wetland_initialize(Wetland_handle* h);
WETLAND_API void   Wetland_initialize_at(Wetland_handle* h, double tstart, double dt0);
/* time stepping: 1 on success, 0 if the solver failed */
WETLAND_API int    Wetland_step(Wetland_handle* h);
WETLAND_API int    Wetland_step_to(Wetland_handle* h, double t_end);  /* one step, dt clamped to t_end */
WETLAND_API int    Wetland_run_to(Wetland_handle* h, double t_end);
/* state access */
WETLAND_API double Wetland_time(const Wetland_handle* h);
WETLAND_API int    Wetland_n_states(void);
WETLAND_API double Wetland_state(const Wetland_handle* h, int i);
WETLAND_API const char* Wetland_state_name(int i);
WETLAND_API double Wetland_simulation_start(void);
WETLAND_API double Wetland_simulation_end(void);
/* parameters (setasparameter bindings, model order) and observations (per accepted step) */
WETLAND_API int    Wetland_n_parameters(void);
WETLAND_API const char* Wetland_parameter_name(int i);
WETLAND_API double Wetland_parameter(const Wetland_handle* h, int i);
WETLAND_API void   Wetland_set_parameter(Wetland_handle* h, int i, double v);
WETLAND_API void   Wetland_apply_parameters(Wetland_handle* h);
WETLAND_API int    Wetland_n_observations(void);
WETLAND_API const char* Wetland_observation_name(int i);
WETLAND_API int    Wetland_observation_count(const Wetland_handle* h, int i);
WETLAND_API int    Wetland_observation_at(const Wetland_handle* h, int i, int k, double* t, double* v);
WETLAND_API void   Wetland_clear_observations(Wetland_handle* h);
/* solver status: a failed solve must not be scored as a good fit */
WETLAND_API int    Wetland_solution_failed(const Wetland_handle* h);
WETLAND_API double Wetland_simulation_duration(const Wetland_handle* h);
WETLAND_API long   Wetland_step_count(const Wetland_handle* h);
WETLAND_API int    Wetland_last_iterations(const Wetland_handle* h);
WETLAND_API void   Wetland_reset_status(Wetland_handle* h);
/* runtime forcing: replace a baked series by (object, quantity) name */
WETLAND_API int    Wetland_n_series(void);
WETLAND_API const char* Wetland_series_object(int k);
WETLAND_API const char* Wetland_series_quantity(int k);
WETLAND_API int    Wetland_set_series(Wetland_handle* h, const char* object, const char* quantity, const double* t, const double* v, int n);
WETLAND_API int    Wetland_set_precipitation(Wetland_handle* h, const char* object, const char* quantity, const double* start, const double* end, const double* depth, int n);
/* state values in/out (hot restart); mass/limited/limitFactor may be NULL */
WETLAND_API void   Wetland_export_state(const Wetland_handle* h, double* storage, double* mass, int* limited, double* limitFactor);
WETLAND_API void   Wetland_import_state(Wetland_handle* h, double t, const double* storage, const double* mass, const int* limited, const double* limitFactor);
WETLAND_API int    Wetland_n_mass(void);
WETLAND_API double Wetland_mass(const Wetland_handle* h, int i);  /* constituent mass, index block*nConst+j */

#ifdef __cplusplus
}
#endif
#endif
